name: SonarQube Scan - Python

on:
  push:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Paso para clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso para instalar las dependencias de Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso para ejecutar el análisis de SonarQube
      - name: Run SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@v3.0.0 
        with: 
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=calculadora-python
        env:
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

