name: SonarQube Scan - Python

on:
  push:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Paso para clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso para instalar el esc치ner de SonarQube
      - name: Install SonarQube Scanner
        run: |
          # Descargar el esc치ner de SonarQube
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          # Descomprimir el archivo
          unzip sonar-scanner.zip
          # Mover el esc치ner
          mv sonar-scanner-4.8.0.2856-linux sonar-scanner
          # Agregar al PATH
          echo "${PWD}/sonar-scanner/bin" >> $GITHUB_PATH

      # Paso para instalar las dependencias de Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso para ejecutar el an치lisis de SonarQube
      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=calculadora-python \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
